name: Build APK
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Abrir o projeto
        run: unzip -q ArenaCraft-APK.zip -d proj

      - name: Colocar o link do jogo
        env:
          LINK: https://sharply-skimming-reliance.ngrok-free.dev
        run: sed -i "s|https://COLOQUE-SEU-LINK.ngrok-free.dev|$LINK|" proj/app/src/main/res/values/strings.xml

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.9

      - name: Compilar APK
        working-directory: proj
        run: gradle assembleDebug --no-daemon

      - uses: actions/upload-artifact@v4
        with:
          name: ArenaCraft-apk
          path: proj/app/build/outputs/apk/debug/app-debug.apk
